apiVersion: v1
kind: Service
metadata:
  name: calico-felix-metrics
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"
    prometheus.io/scheme: http
spec:
  clusterIP: None
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http-metrics
    port: 9091
    targetPort: 9091
  selector:
    k8s-app: calico-node
---
apiVersion: v1
kind: Service
metadata:
  name: calico-controllers-metrics
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9094"
    prometheus.io/scheme: http
spec:
  clusterIP: None
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: http-metrics
    port: 9094
    targetPort: 9094
  selector:
    k8s-app: calico-kube-controllers
---