apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./calico-install.yaml
  - ./calico-bgppeer.yaml
  - ./calico-bgpconfiguration.yaml
  - ./calico-service_metrics.yaml

patchesStrategicMerge:
  - ./overlay/configmap.yaml
  - ./overlay/daemonset.yaml
  - ./overlay/ippool.yaml