apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - ./base/calico.yaml
  - ./base/04-calico-service_metrics.yaml

patchesStrategicMerge:
  - ./overlay/configmap.yaml
  - ./overlay/daemonset.yaml