apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-config
  namespace: netbox
  labels:
    app.kubernetes.io/component: netbox
    app.kubernetes.io/part-of: monitoring
data:
  DB_NAME: netbox
  DB_USER: netbox_user
  DB_PASSWORD: <POSTGRESQL_PASSWORD>
  DB_HOST: fenrir-infra.postgres-cluster.svc
  DB_PORT: "5432"
  DB_SSLMODE: prefer
  DB_CONN_MAX_AGE: "300"
  DB_WAIT_DEBUG: "1"

  REDIS_HOST: netbox-redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DATABASE: "0"
  REDIS_SSL: "False"
  
  REDIS_CACHE_HOST: netbox-redis
  REDIS_CACHE_PORT: "6379"
  REDIS_CACHE_PASSWORD: ""
  REDIS_CACHE_DATABASE: "1"
  REDIS_CACHE_SSL: "False"

  #At least 50 characters in length and contain a mix of letters, numbers, and symbols.
  SECRET_KEY: iRlzFGRvHstmoW0JJx3XXtcvdTT6NrSYwfovg5QbwnyuZ34SfHkX5TcC
  
  CORS_ORIGIN_ALLOW_ALL: "True"
  CORS_ORIGIN_WHITELIST: https://netbox.app.example.id http://netbox.netbox.svc:8080
  
  DEBUG: "True"

  EMAIL_SERVER: localhost
  
  LOGIN_REQUIRED: "True"
  #LOGIN_TIMEOUT: "1209600"
  
  LOGLEVEL: INFO
  
  METRICS_ENABLED: "True"
  
  PAGINATE_COUNT: "200"
  
  REMOTE_AUTH_ENABLED: "False"
  REMOTE_AUTH_BACKEND: "netbox.authentication.RemoteUserBackend"
  REMOTE_AUTH_HEADER: "HTTP_REMOTE_USER"
  REMOTE_AUTH_AUTO_CREATE_USER: "True"
  #REMOTE_AUTH_DEFAULT_GROUPS: ""
  
  TIME_ZONE: Asia/Jakarta
  
  DATE_FORMAT: "j N Y"
  
  #AUTH_LDAP_SERVER_URI:
  #AUTH_LDAP_BIND_DN:
  #AUTH_LDAP_BIND_PASSWORD:
  #AUTH_LDAP_USER_DN_TEMPLATE:
  AUTH_LDAP_START_TLS: "False"
  LDAP_IGNORE_CERT_ERRORS: "True"
  #AUTH_LDAP_USER_SEARCH_BASEDN:
  AUTH_LDAP_USER_SEARCH_ATTR: sAMAccountName
  #AUTH_LDAP_GROUP_SEARCH_BASEDN:
  AUTH_LDAP_GROUP_SEARCH_CLASS: group
  AUTH_LDAP_GROUP_TYPE: GroupOfNamesType
  #AUTH_LDAP_REQUIRE_GROUP_DN:
  #AUTH_LDAP_IS_ADMIN_DN:
  #AUTH_LDAP_IS_SUPERUSER_DN:
  AUTH_LDAP_FIND_GROUP_PERMS: "True"
  #AUTH_LDAP_MIRROR_GROUPS:
  AUTH_LDAP_CACHE_TIMEOUT: "3600"
  AUTH_LDAP_ATTR_FIRSTNAME: givenName
  AUTH_LDAP_ATTR_LASTNAME: sn
  AUTH_LDAP_ATTR_MAIL: mail
---