apiVersion: v1
kind: Service
metadata:
  name: netbox-server
  namespace: netbox
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: netbox-server
    app.kubernetes.io/part-of: netbox
spec:
  ports:
  - name: http-netbox
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: netbox-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: netbox-redis
    app.kubernetes.io/part-of: netbox
  name: netbox-redis
  namespace: netbox
spec:
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: netbox-redis
---