apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbox-certs
  namespace: istio-system
  labels:
    app.kubernetes.io/component: netbox
    app.kubernetes.io/part-of: monitoring
spec:
  secretName: netbox-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
    #name: letsencrypt-prd
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - Valkyrie
    organizationalUnits:
    - "netbox"
    localities:
    - Asgard
    provinces:
    - Yggdrasil
  dnsNames:
  - netbox.app.cluster.local
---