apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &Labels
    app: sak-cicd
    version: v0.1.8
  name: sak-cicd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sak-cicd
  template:
    metadata:
      labels: *Labels
    spec:
      containers:
      - name: sak-cicd
        image: quay.io/firngl/sak-cicd:0.1.8
        command:
        - cat
        tty: true
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi
        securityContext:
          privileged: true
---