apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    name: data-prometheus
    namespace: prometheus
  hostPath:
    path: "/data/prometheus"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-prometheus
  namespace: prometheus
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---