apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    app: prometheus
    type: local
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring-system
spec:
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: data-prometheus
    namespace: prometheus
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/prometheus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-prometheus
  namespace: prometheus
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---