apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-certs
  namespace: prometheus
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: monitoring-system
spec:
  secretName: prometheus-tls
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - Valkyrie
    organizationalUnits:
    - "Prometheus"
    localities:
    - Asgard
    provinces:
    - Yggdrasil
   #streetAddresses:
   #- Vigrid
   #postalCodes:
   #- "12000"
   #serialNumber: "1234567890"
  dnsNames:
  - prometheus
  - prometheus.prometheus
  - prometheus.prometheus.svc
  - prometheus.prometheus.svc.cluster.local
---