apiVersion: v1
kind: ConfigMap
metadata:
  name: node-exporter-config
  namespace: monitoring
  labels:
    app.kubernetes.io/component: node-exporter
    app.kubernetes.io/part-of: monitoring
data:
  web.yml: |
    #tls_server_config:
    #  cert_file: /etc/config/tls.crt
    #  key_file: /etc/config/tls.key
    #basic_auth_users:
    #  prometheus: $2y$10$EYxs8IOG46m9CtpB/XlPxO1ei7E4BjAen0SUv6di7mD4keR/8JO6m
---