apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
    app.kubernetes.io/component: node-exporter
    app.kubernetes.io/part-of: monitoring
spec:
  clusterIP: None
  selector:
    app: node-exporter
  ports:
  - name: http-node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100
  sessionAffinity: ClientIP
---