apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: iam
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: idm
---