apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - name: http-keycloak
    port: 8080
    targetPort: 8080
  #type: LoadBalancer
---