apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
  labels:
    app: keycloak
data:
  root.user: <keycloak_ROOT_USER_BASE64>
  root.password: <keycloak_ROOT_PASSWORD_BASE64>
type: Opaque
---