apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
  labels:
    app: keycloak
data:
  root.username: YWRtaW4=   #admin
  root.password: YWRtaW4=   #admin
type: Opaque
---