apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    app: grafana
    type: local
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
spec:
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: grafana-data
    namespace: grafana
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/grafana"
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
---