apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
    type: local
spec:
  storageClassName: local-sc
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: grafana-pvc
    namespace: grafana
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/grafana"
