apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    app.kubernetes.io/component: grafana
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
---