apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    app: grafana
    type: local
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
spec:
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: data-grafana
    namespace: grafana
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/grafana"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-grafana
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-hostpath
---