apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [server]
    ;domain = 
    ;root_url = 

    [analytics]
    check_for_updates = true
    ;google_analytics_ua_id =
    ;google_tag_manager_id =

    [users]
    allow_sign_up = false
    allow_org_create = false

    [auth.anonymous]
    enabled = false
    hide_version = true

    [auth.google]
    enabled = false
    client_id = CLIENT_ID
    client_secret = CLIENT_SECRET
    scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    auth_url = https://accounts.google.com/o/oauth2/auth
    token_url = https://accounts.google.com/o/oauth2/token
    ;allowed_domains = mycompany.com mycompany.org
    allow_sign_up = false

    [auth.ldap]
    enabled = false
    config_file = /etc/grafana/ldap.toml
    allow_sign_up = false

    [log]
    mode = console

  ldap.toml: |
    [[servers]]
    host = "127.0.0.1"
    port = 389
    use_ssl = false
    start_tls = false
    ssl_skip_verify = false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
    - name: Prometheus
      orgId: 1
    datasources:
    - name: Prometheus
      access: proxy
      editable: false
      isDefault: true
      type: prometheus
      url: http://prometheus.prometheus.svc:9090
      version: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboardproviders
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      disableDeletion: false
      editable: true
      folder: ''
      options:
        path: /var/lib/grafana/dashboards
      orgId: 1
      type: file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-acl
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
data:
  sample.yaml: |
    apiVersion: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-notifiers
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
data:
  sample.yaml: |
    apiVersion: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning-plugins
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
data:
  sample.yaml: |
    apiVersion: 1
---