apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
data:
  grafana.ini: |
    [paths]
    data = /var/lib/grafana
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins

    [analytics]
    check_for_updates = true
    ;google_analytics_ua_id =
    ;google_tag_manager_id =

    [log]
    mode = console

    [auth.ldap]
    enabled = false
    ;config_file = /etc/grafana/ldap.toml
    ;allow_sign_up = true

  ldap.toml: |
    [[servers]]
    host = "127.0.0.1"
    port = 389
    use_ssl = false
    start_tls = false
    ssl_skip_verify = false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
    - name: Prometheus
      orgId: 1
    datasources:
    - name: Prometheus
      access: proxy
      editable: true
      isDefault: true
      type: prometheus
      url: http://prometheus.prometheus.svc.nebula.moratel.id:9090
      version: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboardproviders
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      disableDeletion: false
      editable: true
      folder: ''
      options:
        path: /var/lib/grafana/dashboards
      orgId: 1
      type: file
---