apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certs
  namespace: grafana
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring-system
spec:
  secretName: grafana-tls
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - Valkyrie
    organizationalUnits:
    - "Valhalla Default Certificate"
    localities:
    - Asgard
    provinces:
    - Yggdrasil
   #streetAddresses:
   #- Vigrid
   #postalCodes:
   #- "12000"
   #serialNumber: "1234567890"
  dnsNames:
  - grafana
  - grafana.grafana
  - grafana.grafana.svc
  - grafana.grafana.svc.cluster.local
---