apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    app.kubernetes.io/component: kiali
    app.kubernetes.io/part-of: monitoring
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: kiali
  labels:
    app.kubernetes.io/component: kiali
    app.kubernetes.io/part-of: monitoring
---