apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-certs
  namespace: istio-system
  labels:
    app.kubernetes.io/component: kiali
    app.kubernetes.io/part-of: dashboard
spec:
  secretName: kiali-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
    #name: letsencrypt-prd
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - Valkyrie
    organizationalUnits:
    - "Kiali Istio Console"
    localities:
    - Asgard
    provinces:
    - Yggdrasil
   #streetAddresses: ["Vigrid"]
   #postalCodes: ["12000"]
   #serialNumber: ["1234567890"]
  dnsNames:
  - kiali
  - kiali.kiali.svc
  - kiali.kiali.svc.cluster.local
  - kiali.app.example.id
---