{
 "title": "System Status",
 "tags": [
  "kubernetes",
  "system",
  "linux"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_pod_info, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{node=~\"$node\", namespace=~\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UniFi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"unifi-jakwifi\"}"
    }
   ]
  },
  {
   "title": "prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "grafana",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "kubelet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"kubelet\"}"
    }
   ]
  },
  {
   "title": "cri-o",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"crio\"}"
    }
   ]
  },
  {
   "title": "calico",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "up{service=\"calico-controllers-metrics\"}",
     "legendFormat": "controllers"
    },
    {
     "expr": "up{service=\"calico-felix-metrics\"}",
     "legendFormat": "felix"
    }
   ]
  },
  {
   "title": "CPU Load - $node",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=~\"idle\",node=~\"$node\"}[5m])) by (cpu)",
     "legendFormat": "CPU #{{cpu}}"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "stat",
   "description": "Network traffic in the last hour",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{node=~\"$node\"}[24h]))"
    }
   ]
  },
  { "title": "  ", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "cadvisor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"cadvisor\"}"
    }
   ]
  },
  {
   "title": "kube-apiserver",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{component=\"apiserver\"}"
    }
   ]
  },
  {
   "title": "CoreDNS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{kubernetes_io_name=\"CoreDNS\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "nginx-ingress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_nginx_up{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "cert-manager",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{app=\"cert-manager\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "MetalLB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{app=\"metallb\",node=~\"$node\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "stat",
   "description": "Network traffic in the last hour",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{node=~\"$node\"}[24h]))"
    }
   ]
  },
  {
   "title": "Uptime - $node",
   "type": "stat",
   "description": "Time since $node last boot",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds{node=~\"$node\"} - node_boot_time_seconds{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Basic - $node",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",node=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "busy system"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',node=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "busy user"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',node=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "busy iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",node=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "busy irq"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',node=~\"$node\"}[$__rate_interval])) * 100",
     "legendFormat": "busy other"
    },
    {
     "expr": "(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',node=~\"$node\"}[$__rate_interval])) * 100)",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "System Load - $node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_load1{node=~\"$node\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{node=~\"$node\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{node=~\"$node\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage - $node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$node\"} > 0",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_MemFree_bytes{node=~\"$node\"} > 0",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{node=~\"$node\"} > 0",
     "legendFormat": "available"
    },
    {
     "expr": "node_memory_Cached_bytes{node=~\"$node\"} > 0",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_Active_bytes{node=~\"$node\"} > 0",
     "legendFormat": "active"
    },
    {
     "expr": "node_memory_Inactive_bytes{node=~\"$node\"} > 0",
     "legendFormat": "inactive"
    }
   ]
  },
  {
   "title": "k8s CPU Usage - $node/$namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "k8s Memory Usage - $node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_memory_usage_bytes{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\", container!=\"POD\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "NGINX Ingress - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "stat",
   "description": "NGINX Ingress Controller status on $node nodes.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_nginx_up{node=~\"$node\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": " Number of successful NGINX reloads. This includes the label reason with 2 possible values endpoints (the reason for the reload was an endpoints update) and other (the reload was caused by something other than an endpoint update like an ingress update).",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (reason) (nginx_ingress_controller_nginx_reloads_total{node=~\"$node\"})",
     "legendFormat": "Reloads {{reason}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_nginx_connections_accepted{node=~\"$node\"}[1m]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(increase(nginx_ingress_nginx_connections_handled{node=~\"$node\"}[1m]))",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nginx_ingress_nginx_connections_active{node=~\"$node\"}) by (app) ",
     "legendFormat": "active"
    },
    {
     "expr": "sum(nginx_ingress_nginx_connections_reading{node=~\"$node\"}) by (app) ",
     "legendFormat": "reading"
    },
    {
     "expr": "sum(nginx_ingress_nginx_connections_waiting{node=~\"$node\"}) by (app) ",
     "legendFormat": "waiting"
    },
    {
     "expr": "sum(nginx_ingress_nginx_connections_writing{node=~\"$node\"}) by (app) ",
     "legendFormat": "writing"
    }
   ]
  },
  { "title": "Kubelet - $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{node=~\"$node\"}",
     "legendFormat": "Running Pods"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Nodes: $node",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_containers{node=~\"$node\"}",
     "legendFormat": "Container {{container_state}}"
    }
   ]
  }
 ]
}