kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    app: calico-node
    k8s-app: calico-node
spec:
  template:
    spec:
      containers:
        - name: calico-node
          env:
            - name: IP6
              value: "autodetect"
            - name: FELIX_IPV6SUPPORT
              value: "true"
---