apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config
  namespace: phpmyadmin
  labels:
    app.kubernetes.io/component: phpmyadmin
    app.kubernetes.io/part-of: database
data:
  config.user.inc.php: |
    <?php
    declare(strict_types=1);
    $cfg['blowfish_secret'] = 'yUffDob4kOpKjiWao2MXj5di4qDuGovN';

    $i = 0;

    $i++;
    $cfg['Servers'][$i]['auth_type'] = 'cookie';
    $cfg['Servers'][$i]['host'] = 'mariadb.mariadb.svc';
    $cfg['Servers'][$i]['compress'] = false;
    $cfg['Servers'][$i]['AllowNoPassword'] = false;
---