apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: phpmyadmin-gw
  namespace: phpmyadmin
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http-phpmyadmin
      protocol: HTTP
    hosts:
    - pma.app.cluster.local
  - port:
      number: 443
      name: https-phpmyadmin
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: phpmyadmin-tls
    hosts:
    - pma.app.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
spec:
  hosts:
  - pma.app.cluster.local
  gateways:
  - phpmyadmin-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: phpmyadmin # pods service name
        port:
          number: 80
---