apiVersion: v1
kind: Namespace
metadata:
  name: adminer
  labels:
    app.kubernetes.io/component: adminer
    app.kubernetes.io/part-of: database
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adminer
  namespace: adminer
  labels:
    app.kubernetes.io/component: adminer
    app.kubernetes.io/part-of: database
---