apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adminer-certs
  namespace: istio-system
spec:
  secretName: adminer-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - Valkyrie
    organizationalUnits:
    - "Adminer"
    localities:
    - Asgard
    provinces:
    - Yggdrasil
  dnsNames:
  - adminer
  - adminer.adminer.svc
  - adminer.adminer.svc.cluster.local
  - adminer.app.example.id
---