apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace
  - ./deployment
  - ./istio
  - ./certificate

commonLabels:
  app.kubernetes.io/component: adminer
  app.kubernetes.io/part-of: database
---