apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./namespace.yaml
- ./operator-service-account-rbac.yaml
- ./configmap.yaml
- ./postgres-operator.yaml
- ./api-service.yaml
- ./ui/deployment.yaml
- ./ui/service.yaml
- ./ui/ui-service-account-rbac.yaml
- ./ui/gateway-virtualsvc.yaml
- ./ui/07-postgres-ui-certificate.yaml