apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: influxdb2-certs
  namespace: istio-system
  labels:
    app.kubernetes.io/component: influxdb2
    app.kubernetes.io/part-of: database
spec:
  secretName: influxdb2-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - Valkyrie
    organizationalUnits:
    - "Identity Management"
    localities:
    - Asgard
    provinces:
    - Yggdrasil
  dnsNames:
  - influxdb2
  - influxdb2.influxdb2.svc.cluster.local
  - influxdb2-headless.influxdb2.svc.cluster.local
  - influxdb2-relay.influxdb2.svc.cluster.local
  - influxdb2.app.example.id
---