apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: argocd-server
  namespace: argocd
spec:
  listener:
    name: tls-passthrough
    protocol: TLS_PASSTHROUGH
  host: argocd.cluster.local
  upstreams:
    - name: argocd-server
      service: argocd-server
      port: 443
  action:
    pass: argocd-server
---