apiVersion: v1
kind: Service
metadata:
  name: argocd-lb
  namespace: argocd
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-ingress
---