apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./01-argocd-namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.3/manifests/install.yaml
  - ./06-argocd-istio.yaml
  - ./07-argocd-certificate.yaml

patchesStrategicMerge:
  - ./overlay/configmap.yaml
  - ./overlay/deployment.yaml
  - ./overlay/service.yaml
---