apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-certs
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: monitoring-system
spec:
  secretName: monitoring-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - Valkyrie
    organizationalUnits:
    - "Network Monitoring System"
    localities:
    - Asgard
    provinces:
    - Yggdrasil
   #streetAddresses:
   #- Vigrid
   #postalCodes:
   #- "12000"
   #serialNumber: "1234567890"
  dnsNames:
  - nms.app.cluster.local
---