apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default-controlplane
  namespace: istio-system
spec:
  components:
    base:
      k8s:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
    cni:
      enabled: false
      namespace: kube-system
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-default
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
    - name: istio-ingressgateway-app
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-app
        service:
          ports:
          - name: tcp-3306
            port: 3306
            targetPort: 3306
          - name: tcp-5432
            port: 5432
            targetPort: 5432
          - name: tcp-6379
            port: 6379
            targetPort: 6379
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tcp-50000
            port: 50000
            targetPort: 50000
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      label:
        istio: ingressgateway-app
    - name: istio-ingressgateway-prd
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-prd
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      label:
        istio: ingressgateway-prd
    pilot:
      k8s:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
  profile: default
  #values:
---