apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default-controlplane
  namespace: istio-system
spec:
  components:
    base:
      enabled: true
    cni:
      enabled: false
      namespace: kube-system
      k8s:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
        hpaSpec:
          scaleTargetRef:
            apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
          minReplicas: 1
          maxReplicas: 5
          metrics:
          - type: Resource
            resource:
              name: cpu
              targetAverageUtilization: 80
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-default
        service:
          externalTrafficPolicy: Local  #possible using Calico CrossSubnet rule
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
          - name: tcp
            port: 31400
            targetPort: 31400
          - name: tls
            port: 15443
            targetPort: 15443
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
    - name: istio-ingressgateway-app
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
        service:
          externalTrafficPolicy: Local  #possible using Calico CrossSubnet rule
          ports:
          - name: tcp-3306
            port: 3306
            targetPort: 3306
          - name: tcp-5432
            port: 5432
            targetPort: 5432
          - name: tcp-6379
            port: 6379
            targetPort: 6379
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: tcp-50000
            port: 50000
            targetPort: 50000
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-app
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      label:
        istio: ingressgateway-app
    - name: istio-ingressgateway-prd
      enabled: true
      k8s:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
        service:
          externalTrafficPolicy: Local  #possible using Calico CrossSubnet rule
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
          - name: tcp
            port: 31400
            targetPort: 31400
          - name: tls
            port: 15443
            targetPort: 15443
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-prd
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      label:
        istio: ingressgateway-prd
    pilot:
      k8s:
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 1
  profile: default
---