apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-default-controlplane
  namespace: istio-system
spec:
  components:
    cni:
      enabled: true
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-default
    - name: istio-ingressgateway-stg
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-stg
      label:
        istio: istio-ingressgateway-stg
    - name: istio-ingressgateway-prd
      enabled: true
      k8s:
        serviceAnnotations:
          metallb.universe.tf/address-pool: istio-ingress-prd
      label:
        istio: istio-ingressgateway-prd
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
  profile: default
  values:
    sidecarInjectorWebhook:
      injectedAnnotations:
        k8s.v1.cni.cncf.io/networks: kube-public/istio-cni
    cni:
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/multus/net.d
      cniConfFileName: istio-cni.conf
      chained: false
---