apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-certs
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-stg
  privateKey:
    algorithm: ECDSA
    size: 256
  subject:
    countries:
    - ID
    organizations:
    - "Mora Telematika Indonesia"
    organizationalUnits:
    - "JakWiFi"
    localities:
    - "Jakarta Pusat"
    provinces:
    - "DKI Jakarta"
  dnsNames:
  - stronghold.jakwifi.id
---
