apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
    type: local
spec:
  storageClassName: local-sc
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    name: jenkins-pvc
    namespace: jenkins
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/jenkins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
  labels:
    app: jenkins
spec:
  storageClassName: local-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi