apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    app: jenkins
    type: local
spec:
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: data-jenkins
    namespace: jenkins
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/jenkins"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  storageClassName: local-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---