apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: jenkins
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      name: http-jenkins
      number: 80
      protocol: HTTP
    hosts:
    - "jenkins.app.cluster.local"
  - port:
      name: https-jenkins
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: jenkins-tls
    hosts:
    - "jenkins.app.cluster.local"
  - port:
      name: tcp-jnlp
      number: 50000
      protocol: TCP
    hosts:
    - "jenkins.app.cluster.local"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jenkins
  namespace: jenkins
spec:
  hosts:
  - "jenkins.app.cluster.local"
  gateways:
  - jenkins-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: jenkins.jenkins.svc.cluster.local
        port:
          number: 8080
  tcp:
  - match:
    - port: 50000
    route:
    - destination:
        host: jenkins.jenkins.svc.cluster.local
        port:
          number: 50000
---