apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins-gw
  namespace: jenkins
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http-jenkins
      protocol: HTTP
    hosts:
    - jenkins.dxm.balitbanghub.id
  - port:
      number: 443
      name: https-jenkins
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: jenkins-tls
    hosts:
    - jenkins.dxm.balitbanghub.id
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jenkins
  namespace: jenkins
spec:
  hosts:
  - jenkins.dxm.balitbanghub.id
  gateways:
  - jenkins-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: jenkins # pods service name
        port:
          number: 8080
---