apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb
  labels:
    app: mariadb
    type: local
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
spec:
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: mariadb-data
    namespace: mariadb
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/mariadb"
---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb
  labels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
---