apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: mariadb
  labels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
data:
  my.cnf: |
    [mysqld]
    binlog_format = ROW
    expire_logs_days = 20
    general_log = 0
    innodb_flush_log_at_trx_commit = 0

    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    default_storage_engine = InnoDB
    default_tmp_storage_engine = InnoDB
    lower_case_table_names = 0