apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
  labels: &Labels
    app: mariadb
    #app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
spec:
  serviceName: mariadb
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      securityContext:
        fsGroup: 1001004
      serviceAccountName: mariadb
      containers:
      - name: mariadb-server
        image: mariadb:10.5
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - name: mysql
          containerPort: 3306
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: config
          mountPath: /etc/mysql/conf.d
      terminationGracePeriodSeconds: 300
      volumes:
      - name: config
        configMap:
          name: mariadb-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
      selector:
        matchLabels:
          app: mariadb
      storageClassName: local-hostpath
---
kind: Service
apiVersion: v1
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
spec:
  clusterIP: None
  selector:
    #Should same with StatefullSet spec.selector
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: mysql
  sessionAffinity: ClientIP
---