apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: mariadb
  labels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mariadb
  labels: &Labels
    #app.kubernetes.io/name: $APP_INSTANCE_NAME
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
    k8s-app: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      securityContext:
        fsGroup: 1001001
      serviceAccountName: mariadb
      containers:
      - name: mariadb-server
        image: prom/mariadb:latest
        imagePullPolicy: "IfNotPresent"
        args:
        - --config.file=/mariadb/config/mariadb.yaml
        - --storage.tsdb.path=/mariadb/data
        - --web.console.libraries=/usr/share/mariadb/console_libraries
        - --web.console.templates=/usr/share/mariadb/consoles
        - --web.enable-lifecycle
        ports:
        - name: http-mariadb
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        # based on 10 running nodes with 30 pods each
        resources:
          requests:
            cpu: 200m
            memory: 1000Mi
        volumeMounts:
        - name: config-file
          mountPath: /mariadb/config
        - name: storage-tsdb
          mountPath: /mariadb/data
          subPath: ""
      terminationGracePeriodSeconds: 300
      volumes:
      - name: config-file
        configMap:
          name: mariadb-config
      - name: storage-tsdb
        persistentVolumeClaim:
          claimName: mariadb-data
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - mariadb
            topologyKey: "kubernetes.io/hostname"
---
kind: Service
apiVersion: v1
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app.kubernetes.io/component: mariadb
    app.kubernetes.io/part-of: database
    k8s-app: mariadb
spec:
  clusterIP: None
  selector:
    #Should same with StatefullSet spec.selector
    k8s-app: mariadb
  ports:
  - protocol: TCP
    port: 9090
    targetPort: http-mariadb
  sessionAffinity: ClientIP
---