apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - ./namespace.yaml
  - ./metallb.yaml
  - ./03-metallb-configmap.yaml

patchesStrategicMerge:
  - ./overlay/namespace.yaml
  - ./overlay/deployment.yaml
