apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    app.kubernetes.io/part-of: dashboard
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer
  namespace: portainer
  labels:
    app.kubernetes.io/component: portainer
    app.kubernetes.io/part-of: dashboard
---