apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  labels:
	app: portainer
	type: local
spec:
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
	name: portainer
	namespace: portainer
  capacity:
	storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
	path: "/data/portainer"
---