apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  labels:
    app: portainer
    app.kubernetes.io/part-of: dashboard
    type: local
spec:
  storageClassName: openebs-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: portainer
    namespace: portainer
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/portainer"
---