apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: dmz1-201-pool
  namespace: kube-public
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "ens224.201",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "172.16.10.0/24",
        "rangeStart": "172.16.10.10",
        "rangeEnd": "172.16.10.232",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "172.16.10.1"
      }
    }'
---