apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: kube-public
spec:
  config: '{
      "cniVersion": "0.4.0",
      "type": "macvlan",
      "master": "ens224",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.154.142.0/24",
        "rangeStart": "10.154.142.200",
        "rangeEnd": "10.154.142.220",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.154.142.1"
      }
    }'