apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    app.kubernetes.io/component: minio
    app.kubernetes.io/part-of: storage
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/component: minio
    app.kubernetes.io/part-of: storage
---