apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: minio
  labels:
    app: minio
data:
  accesskey: <MINIO_ROOT_USER_BASE64>
  secretkey: <MINIO_ROOT_PASSWORD_BASE64>
type: Opaque
---