apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels: &Labels
    app.kubernetes.io/component: node-exporter
    app.kubernetes.io/part-of: monitoring-system
    k8s-app: node-exporter
  annotations: &Annotations
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    prometheus.io/scheme: http
spec:
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
      annotations: *Annotations
    spec:
      containers:
      - args:
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
        - --no-collector.nvme
        - --no-collector.wifi
        - --no-collector.hwmon
        - --collector.cpu.info
        #- --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+|var/lib/containers/storage/.+|run/containers/storage/.+)($|/)
        - --collector.filesystem.mount-points-exclude="^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
        - --collector.netclass.ignored-devices="^(veth.*|cali.*)$"
        #- --web.config="/etc/config/web.yml"
        name: node-exporter
        image: prom/node-exporter
        ports:
          - containerPort: 9100
            protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        volumeMounts:
        - name: config-file
          mountPath: "/etc/config/"
        - name: boot
          mountPath: /host/boot
          mountPropagation: HostToContainer
          readOnly: true
        - name: sys
          mountPath: /host/sys
          mountPropagation: HostToContainer
          readOnly: true
        - name: root
          mountPath: /host/root
          mountPropagation: HostToContainer
          readOnly: true
      volumes:
      - name: config-file
        configMap:
          name: node-exporter-config
      - hostPath:
          path: /boot
        name: boot
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/component: node-exporter
    app.kubernetes.io/part-of: monitoring-system
    k8s-app: node-exporter
spec:
  clusterIP: None
  selector:
    k8s-app: node-exporter
  ports:
  - port: 9100
    protocol: TCP
    targetPort: 9100
  sessionAffinity: ClientIP
---