apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs
  labels:
    app: gogs
    type: local
spec:
  storageClassName: local-hostpath
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: gogs-data
    namespace: gogs
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/gogs"
---
apiVersion: v1
kind: Namespace
metadata:
  name: gogs
  labels:
    app.kubernetes.io/component: gogs
    app.kubernetes.io/part-of: git
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gogs
  namespace: gogs
  labels:
    app.kubernetes.io/component: gogs
    app.kubernetes.io/part-of: git
---