apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  labels:
    app.kubernetes.io/part-of: cert-manager
spec:
  ca:
    # Needs to be in the same namespace as the cert-manager controller pod
    secretName: selfsigned-ca
---